Gizmoのページを追加
VRHIKKY/VketCloudSDK_Documents pull request #541
Opened 2024-11-05 11:17 UTC by Naya-Mitamura

ギズモに関するページを追加

2024-11-07 06:20 UTC, Negi-T requested changes

2024-11-07 06:20 UTC, Negi-T commented on docs/WorldEditingTips/Gizmos.ja.md
> +img# Sceneビューにおけるギズモの表示
見出しフォーマット誤り

2024-11-08 09:45 UTC, ra9g16 commented on docs/WorldEditingTips/Gizmos.ja.md
> +img# Sceneビューにおけるギズモの表示
https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/541/commits/92db7e3392d09cb4b32ec41bf0441d2887df3256

こちら修正済みです

2024-11-08 09:54 UTC, Naya-Mitamura commented on docs/WorldEditingTips/Gizmos.ja.md
> +| コンポーネント名 | アイコン |
https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/541/commits/2c1494fdbe18b659cd98dd660fb74f5e9695e618
にて修正

2024-11-08 09:54 UTC, Naya-Mitamura commented on docs/WorldEditingTips/Gizmos.ja.md
> +アイコンは該当コンポーネントの状態によって色が変化します
https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/541/commits/2c1494fdbe18b659cd98dd660fb74f5e9695e618
にて修正

2024-11-08 09:57 UTC, ra9g16 approved these changes
lgtm!

2024-11-08 09:58 UTC, merged