デリゲート関数内でhsItemGetOwnScene()してもアイテムが取得出来ないことがある記事の作成
VRHIKKY/VketCloudSDK_Documents pull request #562
Opened 2024-12-04 09:48 UTC by Naya-Mitamura

[関連チケット](https://hikky.atlassian.net/jira/software/c/projects/LDOC/boards/230?assignee=60640a58b5e55100693d1435&selectedIssue=LDOC-890)

2024-12-06 04:04 UTC, ra9g16 requested changes
以下対応お願いいたします。
①英語の記事をchatgptを使ってよいので、英語に翻訳してください。
②mkdocs.ymlに記事を追加してください。
③changelog-14.4に記事を追加してください

2024-12-06 04:04 UTC, ra9g16 commented on docs/FAQ/hsItemGetOwnScene.jp.md
ファイル名をjp.mdからja.mdにしてください

2024-12-13 01:37 UTC, ra9g16 approved these changes
lgtm

2024-12-13 02:28 UTC, Kondo-Totori approved these changes
LGTM!

2024-12-13 07:45 UTC, Negi-T approved these changes
LGTM!

2024-12-13 08:26 UTC, merged