MeshColliderとHEOAreaColliderを持つコライダーが重なっていた場合、HEOAreaColliderが動作しないペー…
VRHIKKY/VketCloudSDK_Documents pull request #564
Opened 2024-12-04 10:11 UTC by Naya-Mitamura

[関連チケット](https://hikky.atlassian.net/browse/LDOC-885)

2024-12-06 04:05 UTC, ra9g16 requested changes
以下対応お願いいたします。
①英語の記事をchatgptを使ってよいので、英語に翻訳してください。
②mkdocs.ymlに記事を追加してください。
③changelog-14.4に記事を追加してください
④ファイル名をjp.mdからja.mdにしてください

2024-12-13 01:41 UTC, ra9g16 approved these changes
lgtm!

2024-12-13 01:47 UTC, ra9g16 approved these changes
lgtm

2024-12-13 02:36 UTC, Kondo-Totori approved these changes
LGTM!

2024-12-13 09:14 UTC, merged