【課題解決Wiki】iPhone単体でChromeのデベロッパーツールのコンソールを確認する方法 追加
VRHIKKY/VketCloudSDK_Documents pull request #581
Opened 2024-12-26 08:46 UTC by akiRAM2

### **PR Type**
Documentation

___

### **Description**
- iPhone単体でChromeのデベロッパーツールのコンソールを確認する方法を解説する新しいガイドを追加しました。英語版と日本語版の両方を提供しています。
- ガイドでは、手順を画像付きで詳細に説明し、互換性や制限に関する情報も含めています。
- 変更履歴に新しいガイドのエントリを追加しました。
- mkdocsの設定を更新し、新しいガイドのナビゲーションと翻訳エントリを追加しました。

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>iPhoneConsole.en.md</strong><dd><code>Added guide for Chrome Developer Tools console on iPhone (English).</code></dd></summary>
<hr>

docs/WorldMakingGuide/iPhoneConsole.en.md

<li>Added a new guide explaining how to check the Chrome Developer Tools <br>console on iPhone without a computer.<br> <li> Included step-by-step instructions with images for better clarity.<br> <li> Provided additional information about compatibility and limitations.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/581/files#diff-438a5ce18af72b9fcce9b91cc2234b7ec2724a4de9aeead463a2d95aeb2ff3b2">+53/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>iPhoneConsole.ja.md</strong><dd><code>iPhone単体でChromeデベロッパーツールのコンソール確認ガイド追加 (日本語)。</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/WorldMakingGuide/iPhoneConsole.ja.md

<li>日本語でiPhone単体でChromeのデベロッパーツールのコンソールを確認する方法を説明するガイドを追加。<br> <li> 手順を画像付きで詳細に解説。<br> <li> 互換性や制限に関する情報を提供。<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/581/files#diff-204c2eeaf29412863f9f46debef7bebfac9f04cb62012682aea7b92869428b5b">+58/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>changelog-14.2.en.md</strong><dd><code>Updated changelog with new guide entry (English).</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/changelog/changelog-14.2.en.md

<li>Added a changelog entry for the new guide on checking Chrome Developer <br>Tools console on iPhone.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/581/files#diff-2f3baf40cb41ed78decf8d39000daef3a13e7b63f50de72c9d8a685e1356d6bb">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>changelog-14.2.ja.md</strong><dd><code>変更履歴に新しいガイドを追加 (日本語)。</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/changelog/changelog-14.2.ja.md

- 新しいiPhone単体でChromeデベロッパーツールのコンソール確認ガイドの変更履歴を追加。

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/581/files#diff-a8f7442620adccd75c20db969e01eb0df04d1ae71c0bdda20f51ce3726dd1a5b">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>mkdocs.yml</strong><dd><code>Updated mkdocs configuration for new guide.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

mkdocs.yml

<li>Added navigation and translation entries for the new guide in both <br>English and Japanese.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/581/files#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

2025-01-08 03:13 UTC, ra9g16 requested changes
変更のほどよろしくお願いいたします！

2025-01-08 03:13 UTC, ra9g16 commented on docs/WorldMakingGuide/iPhoneConsole.en.md
> +    OS : iOS 16.5.1
`<br>`を加えてください！

2025-01-08 03:13 UTC, ra9g16 commented on docs/WorldMakingGuide/iPhoneConsole.ja.md
> +    OS : iOS 16.5.1
`<br>`を加えてください！

2025-01-10 04:15 UTC, Kondo-Totori commented
全体的に画像のサイズをもう少し小さくしていただけますと幸いです。

![image](https://github.com/user-attachments/assets/e31b7d85-fe6c-442c-a4ae-e49d217bdd28)
文字が画像の右側から始まっている箇所があります。

2025-01-10 06:41 UTC, Negi-T approved these changes
LGTM!

2025-01-16 07:30 UTC, Kondo-Totori approved these changes
LGTM!

2025-01-17 09:06 UTC, ra9g16 approved these changes
lgtm!

2025-01-17 09:06 UTC, merged