【課題解決Wiki】ワールド入室後にマルチプレイができない時の確認ポイント 追加
VRHIKKY/VketCloudSDK_Documents pull request #582
Opened 2024-12-27 03:40 UTC by akiRAM2

### **PR Type**
Documentation

___

### **Description**
- 新しいトラブルシューティングガイド「ワールド入室後にマルチプレイができない時の確認ポイント」を日本語と英語で追加しました。
- ガイドでは、マルチプレイができない場合のケース、原因、解決策を詳細に説明しています。
- 問題解決のための確認リストも提供されています。
- 英語と日本語のchangelogに新しいガイドへのリンクを追加しました。
- mkdocsのナビゲーションと翻訳設定に新しいガイドを反映しました。

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>changelog-14.2.en.md</strong><dd><code>Add link to "Multiplayer Troubleshooting" in English changelog</code></dd></summary>
<hr>

docs/changelog/changelog-14.2.en.md

<li>Added a link to the new "Multiplayer Troubleshooting" page in the <br>troubleshooting section.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/582/files#diff-2f3baf40cb41ed78decf8d39000daef3a13e7b63f50de72c9d8a685e1356d6bb">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>changelog-14.2.ja.md</strong><dd><code>Add links to new troubleshooting pages in Japanese changelog</code></dd></summary>
<hr>

docs/changelog/changelog-14.2.ja.md

<li>Added a link to the new "ワールド入室後にマルチプレイができない時の確認ポイント" page in the <br>troubleshooting section.<br> <li> Added a link to "UnityとVketCloudの見た目をそろえる" page in the troubleshooting <br>section.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/582/files#diff-a8f7442620adccd75c20db969e01eb0df04d1ae71c0bdda20f51ce3726dd1a5b">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>MultiplayerTroubleshooting.en.md</strong><dd><code>Add English troubleshooting guide for multiplayer issues</code>&nbsp; </dd></summary>
<hr>

docs/troubleshooting/MultiplayerTroubleshooting.en.md

<li>Added a new troubleshooting guide for multiplayer issues after <br>entering a world.<br> <li> Included detailed cases, causes, and solutions for common multiplayer <br>problems.<br> <li> Provided a checklist for resolving multiplayer issues.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/582/files#diff-035a4fadb71bfbba8bd61caf95a8d598352d24c1ec0f7e6b5490d7e6f2372fa4">+59/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>MultiplayerTroubleshooting.ja.md</strong><dd><code>マルチプレイ問題に関する日本語トラブルシューティングガイドを追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/troubleshooting/MultiplayerTroubleshooting.ja.md

<li>新しいトラブルシューティングガイド「ワールド入室後にマルチプレイができない時の確認ポイント」を追加。<br> <li> 一般的なマルチプレイ問題のケース、原因、解決策を詳細に記載。<br> <li> 問題解決のための確認リストを提供。<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/582/files#diff-d5dae7d9e321f9add17c45f1e51e64aaf8666bdff9f7915d819ce97503a05bc7">+57/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>mkdocs.yml</strong><dd><code>Update mkdocs configuration for new troubleshooting guide</code></dd></summary>
<hr>

mkdocs.yml

<li>Added "Multiplayer Troubleshooting" to the navigation and translation <br>sections.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/582/files#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

2025-01-10 04:22 UTC, Kondo-Totori commented
「先方の」は無くてもよい気がします。

2025-01-10 04:23 UTC, Kondo-Totori commented
・playground環境でworldidがworldではないか

こちらは不要です。

2025-01-10 06:20 UTC, Negi-T requested changes

2025-01-10 06:20 UTC, Negi-T commented on docs/changelog/changelog-14.2.ja.md
> +    - [UnityとVketCloudの見た目をそろえる](https://vrhikky.github.io/VketCloudSDK_Documents/14.2/heoexporter/he_align_unity_to_vketcloud.html)
トル

2025-01-16 07:34 UTC, Kondo-Totori approved these changes
LGTM!

2025-01-17 09:06 UTC, ra9g16 approved these changes
lgtm!

2025-01-17 09:44 UTC, merged