Sprit関数についてのFAQページを追加
VRHIKKY/VketCloudSDK_Documents pull request #584
Opened 2024-12-27 09:45 UTC by Naya-Mitamura

2025-01-06 04:14 UTC, ra9g16 requested changes
変更のほどよろしくお願いいたします！

2025-01-06 04:14 UTC, ra9g16 commented on docs/FAQ/HS_Sprit.ja.md
> +```
csharpとつけて、色付ける

2025-01-06 04:14 UTC, ra9g16 commented on docs/FAQ/HS_Sprit.en.md
> +```
csharpとつける

2025-01-10 06:24 UTC, Negi-T requested changes

2025-01-10 06:24 UTC, Negi-T commented on docs/changelog/changelog-14.2.ja.md
> +    - [Sprit関数について](https://vrhikky.github.io/VketCloudSDK_Documents/14.2/FAQ/HS_Sprit.html)
Sprit --> Split

2025-01-10 06:24 UTC, Negi-T commented on mkdocs.yml
> +    -　About the Split Function: FAQ/HS_Sprit.md
Sprit --> Split

2025-01-10 06:24 UTC, Negi-T commented on docs/FAQ/HS_Sprit.ja.md
> +![HSSprit](img/HSSprit.jpg)
Sprit --> Split

2025-01-10 06:24 UTC, Negi-T commented on docs/FAQ/HS_Sprit.ja.md
> +# Sprit関数について
Sprit --> Split

2025-01-10 06:24 UTC, Negi-T commented on docs/FAQ/HS_Sprit.en.md
> +![HSSprit](img/HSSprit.jpg)
Sprit --> Split

2025-01-10 09:34 UTC, Negi-T approved these changes
LGTM

2025-01-10 09:39 UTC, ra9g16 approved these changes
lgtm!

2025-01-10 09:40 UTC, merged